### ISSUE TITLE
Ran inside gdb - info and backtrace on Segmentation fault error that occurs during spidering

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#15]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5d21700 (LWP 3781)]
__memmove_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2937
2937    ../sysdeps/x86_64/multiarch/memcpy-ssse3.S: No such file or directory.

(gdb) bt
#0  __memmove_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2937
#1  0x00009080d83469c6 in ?? ()
#2  0x2ca3889b00000000 in ?? ()
#3  0x002f3a7370747468 in ?? ()
#4  0x0000000000000000 in ?? ()

**Comment by MikeLx** [comment]
Haven't seen this again since move to new kernel.
