### ISSUE TITLE
RdbMapp: adedkey out of order.

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#17]
This seems to happen when merging and spidering is running at the same time. I believe the original version of gigablast paused spidering while merging. It may be a good idea to implement that again. Had to run this twice so error happened twice. First time it wasn't running inside gdb. Ran it again inside gdb. Same error. Ran backtrace. Also included directory listing of this collection. Looks like no .idx nor .map file for posdb0025 because it aborted in the middle of merging. Moved posdb0025.dat out of coll directory to get it running again, which works but I believe loses data. Output is below. It's still not dumping the core even though it's reporting core dumped or if it is dumping a core I can't find it.

Also thank you for the quick fix to the ticketmaster httpmime error. 

20170131-112244-461 0000 015673 INF build: http://www.fujinon.com/ redirected to http://www.fujifilmusa.com/products/optical_devices/index.html
20170131-112244-484 0000 015673 INF db: Get list took 1 ms. 22956 positive. 0 negative.
20170131-112244-492 0000 015673 INF db: Get list took 0 ms. 20868 positive. 0 negative.
20170131-112244-532 0000 015673 INF db: Get list took 2 ms. 31489 positive. 0 negative.
20170131-112244-554 0000 015673 INF db: Get list took 1 ms. 21227 positive. 0 negative.
20170131-112244-580 0000 015673 INF db: Get list took 4 ms. 34550 positive. 0 negative.
20170131-112244-582 0000 015673 LOG build: RdbMap: added key out of order. count=1 file=/mnt/sam850pro2tb0/open-source-search-engine/coll.dmozseed.1/posdb0025.map.
20170131-112244-582 0000 015673 LOG build: offset=30723648 k1=0x414d5b99898b16042d1e7001fa02481cca01 k2=0x414d5b99898b04b9c11edc01441bebc8aa01
20170131-112244-582 0000 015673 ERR gb: Printing stack trace
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x53b06b
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4d7bd7
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4ff476
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4ff4a0
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x5ec17f
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x5ec5d3
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4eaf08
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4eab82
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4eb5fc
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4208dc
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x45e7f8
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x45f28d00
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x53b84d
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x53bac5
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x40ba2c
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x407558
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x7f4b52f7d184
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x7f4b513bf37d
Aborted (core dumped)
235266 charset=UTF-8 ctype=html lang=01(en) country=00(zz) hopcount=01 contentlen=080950 contenttruncated=0 robotstxtlen=0811 robotsallowed=1 ch32=1478598685 dh32=0640164141 sh32=1092221853 ispermalink=1 isrss=0 hasrssoutlink=0 outlinksadded=0057 addlistsize=43874 addspiderreqsize=00000 addspiderrepsize=00076 addstatusdocsize=00000 thumbnail=none utf8size=80951 rawutf8size=81398 priority=0 urlfilternum=14 site=www.feeln.com siteroot=0 pathdepth=1 contentinjected=0 urlinjected=0 isaddurl=0 spiderlinks=1 crawldelayms=500 exactcontenthash=488149790089515632 isadult=0 errcnt=0 redir=http://www.feeln.com/films/meet_my_valentine url=https://www.feeln.com/films/meet_my_valentine : Success
20170131-112244-461 0000 015673 INF build: http://www.fujinon.com/ redirected to http://www.fujifilmusa.com/products/optical_devices/index.html
20170131-112244-484 0000 015673 INF db: Get list took 1 ms. 22956 positive. 0 negative.
20170131-112244-492 0000 015673 INF db: Get list took 0 ms. 20868 positive. 0 negative.
20170131-112244-532 0000 015673 INF db: Get list took 2 ms. 31489 positive. 0 negative.
20170131-112244-554 0000 015673 INF db: Get list took 1 ms. 21227 positive. 0 negative.
20170131-112244-580 0000 015673 INF db: Get list took 4 ms. 34550 positive. 0 negative.
20170131-112244-582 0000 015673 LOG build: RdbMap: added key out of order. count=1 file=/mnt/sam850pro2tb0/open-source-search-engine/coll.dmozseed.1/posdb0025.map.
20170131-112244-582 0000 015673 LOG build: offset=30723648 k1=0x414d5b99898b16042d1e7001fa02481cca01 k2=0x414d5b99898b04b9c11edc01441bebc8aa01
20170131-112244-582 0000 015673 ERR gb: Printing stack trace
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x53b06b
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4d7bd7
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4ff476
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4ff4a0
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x5ec17f
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x5ec5d3
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4eaf08
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4eab82
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4eb5fc
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x4208dc
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x45e7f8
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x45f28d
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x53b84d
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x53bac5
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x40ba2c
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x407558
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x7f4b52f7d184
20170131-112244-582 0000 015673 ERR addr2line -e ./gb 0x7f4b513bf37d
Aborted (core dumped)
root@localhost:/mnt/sam850pro2tb0/open-source-search-engine# ^C
root@localhost:/mnt/sam850pro2tb0/open-source-search-engine# ls *core*
ls: cannot access *core*: No such file or directory
root@localhost:/mnt/sam850pro2tb0/open-source-search-engine# gdb ./gb
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./gb...done.
(gdb) run ./gb
Starting program: /mnt/sam850pro2tb0/open-source-search-engine/gb ./gb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5d21700 (LWP 22118)]
[New Thread 0x7ffff4d1f700 (LWP 22119)]
[New Thread 0x7fffdffec700 (LWP 22120)]
[New Thread 0x7fffdf7eb700 (LWP 22121)]
[New Thread 0x7fffdefea700 (LWP 22122)]
[New Thread 0x7fffde7e9700 (LWP 22123)]
[New Thread 0x7fffddfe8700 (LWP 22124)]
[New Thread 0x7fffdd7e7700 (LWP 22125)]
[New Thread 0x7fffdcfe6700 (LWP 22126)]
[New Thread 0x7fffdc7e5700 (LWP 22127)]
[New Thread 0x7fffdbfe4700 (LWP 22128)]
[New Thread 0x7fffdb7e3700 (LWP 22129)]
[New Thread 0x7fffdafe2700 (LWP 22130)]
[New Thread 0x7fffda7e1700 (LWP 22131)]
[New Thread 0x7fffd9fe0700 (LWP 22132)]
[New Thread 0x7fffd97df700 (LWP 22133)]
[New Thread 0x7fffd8fde700 (LWP 22134)]
20170131-152120-525 0000 022118 INI conf: Gigablast Version      : Jan 31 2017 05:33:07
20170131-152120-525 0000 022118 INI conf: Gigablast Architecture : 64-bit
20170131-152120-525 0000 022118 INI conf: Gigablast Build config : release
20170131-152120-525 0000 022118 INI conf: Gigablast Git commit   : cf08cf428620def41d2a29ce22748134d973cb93
20170131-152120-525 0000 022118 DBG host: Working directory is /mnt/sam850pro2tb0/open-source-search-engine/
20170131-152120-525 0000 022118 DBG host: Using /mnt/sam850pro2tb0/open-source-search-engine/hosts.conf
20170131-152120-525 0000 022118 DBG host: Process ID is 22114
20170131-152120-525 0000 022118 DBG host: Detected local ip 127.0.0.1
20170131-152120-525 0000 022118 DBG host: Detected local ip 192.168.0.30
20170131-152120-525 0000 022118 DBG host: Running as host id #0
20170131-152120-527 0000 022118 INF wikt: Loading /mnt/sam850pro2tb0/open-source-search-engine/wiktionary-syns.dat
20170131-152120-636 0000 022118 INF wikt: Loading /mnt/sam850pro2tb0/open-source-search-engine/wiktionary-buf.txt
20170131-152120-668 0000 022118 DBG wikt: test "love" -> "en|love,loved,loving,loves"
20170131-152120-668 0000 022118 INF wiki: Loading /mnt/sam850pro2tb0/open-source-search-engine/wikititles2.dat
20170131-152120-703 0000 022118 INF mem: addMem(100663296): tbl-wiki. ptr=0x7fffcb04d014 used=126833605
20170131-152120-791 0000 022118 INF db: Loading conf for collection dmozseed (1)
20170131-152120-792 0000 022118 DBG table: grewtable enttbl from 4096 to 8192 slots in 0 ms (this=0xd22fc0) (used=2048)
20170131-152120-792 0000 022118 WRN coll: fixing process count this round for dmozseed
20170131-152120-792 0000 022118 INF db: Loading conf for collection main (0)
20170131-152120-799 0000 022118 INI db: Loading statsdb-saved.dat.
20170131-152120-801 0000 022118 DBG Cleaning up any unfinished merges of collectionless statsdb
20170131-152120-801 0000 022118 DBG Found 9 .dat files for statsdb
20170131-152120-801 0000 022118 DBG Found 0 .dat files for statsdb in merge-space
20170131-152120-801 0000 022118 DBG Cleaned up any unfinished merges of collectionless statsdb
20170131-152120-923 0000 022118 INF mem: addMem(349879400): buckets-posdb. ptr=0x7fffb5e4f014 used=238889050
20170131-152120-924 0000 022118 INI db: Loading posdb-buckets-saved.dat.
20170131-152121-140 0000 022118 WRN db: bucket's last key was out of order!!!!!key was: 04b9c11edc01441bebc8aa01 vs prev: 16042d1e7001fa02481cca01 num keys: 4494 ks=18 bucketNum=3024
20170131-152121-263 0000 022118 INF mem: addMem(349879400): buckets-posdb. ptr=0x7fffa10a3014 used=588768512
20170131-152122-710 0000 022118 INF mem: rmMem (349879400): ptr=0x7fffb5e4f014 buckets-posdb.
20170131-152122-713 0000 022118 INF db: RdbBuckets repair for 9888020 keys complete
20170131-152122-783 0000 022118 INF mem: addMem(193164080): mem-titledb. ptr=0x7fffbecac014 used=596680530
20170131-152122-846 0000 022118 INI db: Loading titledb-saved.dat.
20170131-152122-921 0000 022118 INI db: Loading tagdb-saved.dat.
20170131-152123-124 0000 022118 INF mem: addMem(100000022): mem-spiderdb. ptr=0x7fff96cc9014 used=1006057188
20170131-152123-157 0000 022118 INI db: Loading spiderdb-saved.dat.
20170131-152123-243 0000 022118 INI db: Loading doledb-saved.dat.
20170131-152123-262 0000 022118 INI db: Loading clusterdb-saved.dat.
20170131-152123-286 0000 022118 INI db: Loading linkdb-saved.dat.
20170131-152123-345 0000 022118 WRN disk: read buf is NULL. malloc failed?
20170131-152123-345 0000 022118 WRN disk: readwrite: Buf too small
20170131-152123-345 0000 022118 ERR RdbIndex.cpp:readIndex2:273: Had error reading offset=16 from posdb-saved.idx: Buf too small
20170131-152123-345 0000 022118 WRN db: Could not read index file posdb-saved.idx
20170131-152123-345 0000 022118 INF db: Attempting to generate index file /mnt/sam850pro2tb0/open-source-search-engine/coll.main.0/posdb-saved.dat. May take a while.
20170131-152123-345 0000 022118 INF db: Generating index for posdb buckets
20170131-152123-345 0000 022118 INF db: Index generation succeeded.
20170131-152123-345 0000 022118 INF db: Saving posdb-saved.idx
20170131-152123-345 0000 022118 INF db: Saved 0 index keys for posdb
20170131-152123-345 0000 022118 DBG Cleaning up any unfinished merges of main posdb
20170131-152123-345 0000 022118 DBG Found 0 .dat files for posdb
20170131-152123-345 0000 022118 DBG Found 0 .dat files for posdb in merge-space
20170131-152123-345 0000 022118 DBG Cleaned up any unfinished merges of main posdb
20170131-152123-345 0000 022118 INF db: Generating global index for posdb
20170131-152123-345 0000 022118 DBG Cleaning up any unfinished merges of main titledb
20170131-152123-345 0000 022118 DBG Found 0 .dat files for titledb
20170131-152123-345 0000 022118 DBG Found 0 .dat files for titledb in merge-space
20170131-152123-345 0000 022118 DBG Cleaned up any unfinished merges of main titledb
20170131-152123-345 0000 022118 DBG Cleaning up any unfinished merges of main tagdb
20170131-152123-345 0000 022118 DBG Found 0 .dat files for tagdb
20170131-152123-345 0000 022118 DBG Found 0 .dat files for tagdb in merge-space
20170131-152123-345 0000 022118 DBG Cleaned up any unfinished merges of main tagdb
20170131-152123-345 0000 022118 DBG Cleaning up any unfinished merges of main clusterdb
20170131-152123-345 0000 022118 DBG Found 0 .dat files for clusterdb
20170131-152123-345 0000 022118 DBG Found 0 .dat files for clusterdb in merge-space
20170131-152123-345 0000 022118 DBG Cleaned up any unfinished merges of main clusterdb
20170131-152123-346 0000 022118 DBG Cleaning up any unfinished merges of main linkdb
20170131-152123-346 0000 022118 DBG Found 0 .dat files for linkdb
20170131-152123-346 0000 022118 DBG Found 0 .dat files for linkdb in merge-space
20170131-152123-346 0000 022118 DBG Cleaned up any unfinished merges of main linkdb
20170131-152123-346 0000 022118 DBG Cleaning up any unfinished merges of main spiderdb
20170131-152123-346 0000 022118 DBG Found 0 .dat files for spiderdb
20170131-152123-346 0000 022118 DBG Found 0 .dat files for spiderdb in merge-space
20170131-152123-346 0000 022118 DBG Cleaned up any unfinished merges of main spiderdb
20170131-152123-346 0000 022118 DBG Cleaning up any unfinished merges of main doledb
20170131-152123-346 0000 022118 DBG Found 0 .dat files for doledb
20170131-152123-346 0000 022118 DBG Found 0 .dat files for doledb in merge-space
20170131-152123-346 0000 022118 DBG Cleaned up any unfinished merges of main doledb
20170131-152123-346 0000 022118 DBG Cleaning up any unfinished merges of dmozseed posdb
20170131-152123-346 0000 022118 DBG Found 6 .dat files for posdb
20170131-152123-346 0000 022118 DBG Found 0 .dat files for posdb in merge-space
20170131-152123-346 0000 022118 DBG Cleaned up any unfinished merges of dmozseed posdb
20170131-152123-355 0000 022118 ERR RdbMap.cpp:readMap:300: Map file [posdb0025.map] does not exist.
20170131-152123-356 0000 022118 INF db: Attempting to generate map file for data file posdb0025.dat* of 30887370 bytes. May take a while.
20170131-152123-356 0000 022118 INF db: Generating map for /mnt/sam850pro2tb0/open-source-search-engine/coll.dmozseed.1/posdb0025.dat
20170131-152123-473 0000 022118 LOG build: RdbMap: added key out of order. count=1 file=/mnt/sam850pro2tb0/open-source-search-engine/coll.dmozseed.1/posdb0025.map.
20170131-152123-473 0000 022118 LOG build: offset=30723648 k1=0x414d5b99898b16042d1e7001fa02481cca01 k2=0x414d5b99898b04b9c11edc01441bebc8aa01
20170131-152123-473 0000 022118 ERR gb: Printing stack trace
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x53b06b
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x4d7bd7
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x4ff476
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x4ff4a0
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x5ec17f
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x5ed890
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x55e5a2
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x55ed21
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x5613a1
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x5615d5
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x55583b
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x42966b
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x4295fb
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x40b4ca
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x407558
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x7ffff7bc4184
20170131-152123-479 0000 022118 ERR addr2line -e /mnt/sam850pro2tb0/open-source-search-engine/gb 0x7ffff602037d

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff5d21700 (LWP 22118)]
0x00007ffff5f5cc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5f5cc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5f60028 in __GI_abort () at abort.c:89
#2  0x00000000004d7c08 in Process::shutdownAbort (this=0x149ea80 <g_process>, save_on_abort=false) at Process.cpp:572
#3  0x00000000004ff476 in gbshutdownAbort (save_on_abort=false) at Sanity.cpp:5
#4  0x00000000004ff4a0 in gbshutdownCorrupted () at Sanity.cpp:17
#5  0x00000000005ec17f in RdbMap::addRecord (this=this@entry=0x7ffff06d0a30,
    key=key@entry=0x7ffff5d1ee00 "\001\252\310\353\033D\001\334\036\301\271\004\213\211\231[MA",
    rec=rec@entry=0x7fff8b18fec8 "\003\252\310\353\033D\001\334\036\301\271\004\a\312\bH\\\341\003\352\370+v\003\201\215\303\323 \026\a\352\370\253\206\006\a\342\370\353\270\006\a¸\002\217\a\azx\002\314\n\a\212x\202\062\v\a\252x*$\020\a\272\270)}\021\a2\270@\361\022\a\272\264h9\023\a\272\270h<\023\aʴ\350U\023\aҴhq\023\a\n8\300\232\024\a\n8@\235\024\a\n8\300\237\024\a\n\270", recSize=12) at RdbMap.cpp:687
#6  0x00000000005ed890 in RdbMap::generateMap (this=this@entry=0x7ffff06d0a30, f=f@entry=0x7ffff00618b0) at RdbMap.cpp:1523
#7  0x000000000055e5a2 in RdbBase::addFile (this=this@entry=0x7ffff0269110, isNew=isNew@entry=false, fileId=25, fileId2=-1, mergeNum=-1,
    endMergeFileId=<optimized out>, isInMergeDir=false) at RdbBase.cpp:989
#8  0x000000000055ed21 in RdbBase::loadFilesFromDir (this=this@entry=0x7ffff0269110,
    dirName=dirName@entry=0x7ffff02731ac "/mnt/sam850pro2tb0/open-source-search-engine/coll.dmozseed.1", isInMergeDir=isInMergeDir@entry=false)
    at RdbBase.cpp:743
#9  0x00000000005613a1 in RdbBase::setFiles (this=0x7ffff0269110) at RdbBase.cpp:506
#10 0x00000000005615d5 in RdbBase::init (this=this@entry=0x7ffff0269110, dir=0x14219e4 <g_hostdb+110692> "/mnt/sam850pro2tb0/open-source-search-engine/",
    dbname=dbname@entry=0x15482c8 <g_posdb+8> "posdb", fixedDataSize=0, minToMergeArg=-1, useHalfKeys=true, keySize=18 '\022', pageSize=32768,
    coll=0x7ffff0061b22 "dmozseed", collnum=1, tree=0x0, buckets=0x1548468 <g_posdb+424>, dump=0x1548508 <g_posdb+584>, rdb=0x15482c0 <g_posdb>,
    useIndexFile=true) at RdbBase.cpp:275
#11 0x000000000055583b in Rdb::addRdbBase2 (this=0x15482c0 <g_posdb>, collnum=<optimized out>) at Rdb.cpp:486
#12 0x000000000042966b in Collectiondb::addRdbBasesForCollRec (this=0xd1f700 <g_collectiondb>, cr=0x7ffff0061b10) at Collectiondb.cpp:477
#13 0x00000000004295fb in Collectiondb::addRdbBaseToAllRdbsForEachCollRec (this=0xd1f700 <g_collectiondb>) at Collectiondb.cpp:454
#14 0x000000000040b4ca in main2 (argc=2, argv=0x7fffffffe658) at main.cpp:1908
#15 0x0000000000407558 in main2_trampoline () at main.cpp:190
#16 0x00007ffff7bc4184 in start_thread (arg=0x7ffff5d21700) at pthread_create.c:312
#17 0x00007ffff602037d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

root@localhost:/mnt/sam850pro2tb0/open-source-search-engine/coll.dmozseed.1# ls -l
total 26567668
-rw-rw-r-- 1 root root    5729964 Jan 31 09:45 clusterdb0001.dat
-rw-rw-r-- 1 root root      78388 Jan 31 09:45 clusterdb0001.map
-rw-rw-r-- 1 root root      24132 Jan 31 11:20 coll.conf
-rw-rw-r-- 1 root root        108 Jan 31 11:20 globalcrawlinfo.dat
-rw-rw-r-- 1 root root         16 Jan 31 11:20 ipstouseproxiesfor.dat
-rw-rw-r-- 1 root root 1340871896 Jan 30 23:32 linkdb0001.dat
-rw-rw-r-- 1 root root    1227690 Jan 30 23:32 linkdb0001.map
-rw-rw-r-- 1 root root  181264076 Jan 31 07:03 linkdb0003.dat
-rw-rw-r-- 1 root root     166020 Jan 31 07:03 linkdb0003.map
-rw-rw-r-- 1 root root  287083832 Jan 31 09:16 linkdb0017.dat
-rw-rw-r-- 1 root root     262920 Jan 31 09:16 linkdb0017.map
-rw-rw-r-- 1 root root  274942556 Jan 31 09:01 linkdb0021.dat
-rw-rw-r-- 1 root root     251790 Jan 31 09:01 linkdb0021.map
-rw-rw-r-- 1 root root  274915312 Jan 31 11:17 linkdb0023.dat
-rw-rw-r-- 1 root root     251760 Jan 31 11:17 linkdb0023.map
-rw-rw-r-- 1 root root        108 Jan 31 11:20 localcrawlinfo.dat
-rw-rw-r-- 1 root root 2013265920 Jan 30 23:29 posdb0001.dat
-rw-rw-r-- 1 root root 2013265920 Jan 30 23:30 posdb0001.dat.part1
-rw-rw-r-- 1 root root 2013265920 Jan 30 23:31 posdb0001.dat.part2
-rw-rw-r-- 1 root root 1374520452 Jan 30 23:31 posdb0001.dat.part3
-rw-rw-r-- 1 root root    2607144 Jan 31 02:21 posdb0001.idx
-rw-rw-r-- 1 root root    4525410 Jan 30 23:31 posdb0001.map
-rw-rw-r-- 1 root root  972906690 Jan 31 07:13 posdb0003.dat
-rw-rw-r-- 1 root root     301640 Jan 31 07:13 posdb0003.idx
-rw-rw-r-- 1 root root     593870 Jan 31 07:13 posdb0003.map
-rw-rw-r-- 1 root root 1611068154 Jan 31 09:43 posdb0017.dat
-rw-rw-r-- 1 root root     591368 Jan 31 09:43 posdb0017.idx
-rw-rw-r-- 1 root root     983370 Jan 31 09:43 posdb0017.map
-rw-rw-r-- 1 root root 1592214858 Jan 31 09:31 posdb0021.dat
-rw-rw-r-- 1 root root     446472 Jan 31 09:31 posdb0021.idx
-rw-rw-r-- 1 root root     971870 Jan 31 09:31 posdb0021.map
-rw-rw-r-- 1 root root  903807924 Jan 31 11:15 posdb0023.dat
-rw-rw-r-- 1 root root     292864 Jan 31 11:15 posdb0023.idx
-rw-rw-r-- 1 root root     551710 Jan 31 11:15 posdb0023.map
-rw-rw-r-- 1 root root   30887370 Jan 31 11:22 posdb0025.dat
-rw-rw-r-- 1 root root      18208 Jan 31 11:20 posdb-saved.idx
-rw-rw-r-- 1 root root 2013265920 Jan 31 11:09 spiderdb0001.dat
-rw-rw-r-- 1 root root  590171211 Jan 31 11:10 spiderdb0001.dat.part1
-rw-rw-r-- 1 root root    1430166 Jan 31 11:10 spiderdb0001.map
-rw-rw-r-- 1 root root  102735102 Jan 31 11:20 spiderdb0003.dat
-rw-rw-r-- 1 root root      56496 Jan 31 11:20 spiderdb0003.map
-rw-rw-r-- 1 root root   48474509 Jan 31 05:24 tagdb0001.dat
-rw-rw-r-- 1 root root     852150 Jan 31 05:24 tagdb0001.map
-rw-rw-r-- 1 root root 2013265920 Jan 30 23:31 titledb0001-000.dat
-rw-rw-r-- 1 root root 2013265920 Jan 30 23:31 titledb0001-000.dat.part1
-rw-rw-r-- 1 root root 1832350839 Jan 30 23:32 titledb0001-000.dat.part2
-rw-rw-r-- 1 root root    2503230 Jan 30 23:32 titledb0001.map
-rw-rw-r-- 1 root root  731218357 Jan 31 07:15 titledb0003-000.dat
-rw-rw-r-- 1 root root     312468 Jan 31 07:15 titledb0003.map
-rw-rw-r-- 1 root root 1034801589 Jan 31 09:11 titledb0017-000.dat
-rw-rw-r-- 1 root root     442164 Jan 31 09:11 titledb0017.map
-rw-rw-r-- 1 root root  870027991 Jan 31 08:55 titledb0021-000.dat
-rw-rw-r-- 1 root root     371772 Jan 31 08:55 titledb0021.map
-rw-rw-r-- 1 root root 1040414415 Jan 31 11:19 titledb0023-000.dat
-rw-rw-r-- 1 root root     444558 Jan 31 11:19 titledb0023.map
-rw-rw-r-- 1 root root    4544720 Jan 31 05:27 waitingtree-saved.dat

**Comment by MikeLx** [comment]
I lowered the number of spiders to a level that wouldn't push the active UDP transactions over 80/host and this problem hasn't happened since. It's definitely load related. The original gigablast system simply had the host go dead (not answer new connections) when the number of active UDP transactions went too high for too long without being answered. That way, they couldn't pile up to the point data evaporated. Because system power can vary greatly from system to system, it's likely that each system will need to be "tuned" to whatever number of active UDP transactions it can handle. What might be useful is to have a parm setting for maximum number of active UDP transactions per host. When a host hits that maximum, it doesn't initiate new transactions (i.e. it throttles down.) Essentially, what may be needed is a "rev limiter," to use an automotive term. Just a thought...
