### ISSUE TITLE
Segmentation fault when starting up node

### ISSUE THREAD

**Issue by Gurgel100** [privacore/open-source-search-engine#44]
Hello,
we didn't had much problems with the gigablast instances running on our servers. However some nodes occasionally crash and restart which is indicated by an 'x' in the list where all nodes are listed. But recently one node crash while starting up with a segmentation fault while copying memory. Also each following startup results in the same result.
Our nodes are running on the newest commit of the stable branch.
Here I attach you the logfile and the stacktrace. If you need the bigger stacktrace or the core dump let me know.
The cause to which I traced back the crash is because the field 'm_listPtrHi' is NULL. Why it's NULL I didn't find out.

lastlog.log:
```
20180121-025231-325 0006 017124 INI conf: Gigablast Version      : Aug 18 2017 18:21:37
20180121-025231-325 0006 017124 INI conf: Gigablast Architecture : 64-bit
20180121-025231-325 0006 017124 INI conf: Gigablast Build config : release-safe
20180121-025231-325 0006 017124 INI conf: Gigablast Git commit   : 883a649c4ba5884d7b1e8f2a5b92190708764a70-dirty
20180121-025231-325 0006 017124 DBG host: Working directory is /srv/gigablast/host6/
20180121-025231-325 0006 017124 DBG host: Using /srv/gigablast/host6/hosts.conf
20180121-025231-325 0006 017124 DBG host: Process ID is 17123
20180121-025231-325 0006 017124 DBG host: Detected local ip 127.0.0.1
20180121-025231-325 0006 017124 DBG host: Detected local ip xxx.xxx.xxx.xxx
20180121-025231-325 0006 017124 DBG host: Running as host id #6
20180121-025231-938 0006 017124 DBG wikt: test "love" -> "en|love,loved,loving,loves"
20180121-025232-295 0006 017124 DBG table: grewtable enttbl from 4096 to 8192 slots in 0 ms (this=0x55e05dedef60) (used=2048)
20180121-025232-303 0006 017124 INI db: Loading posdb-buckets-saved.dat.
20180121-025232-433 0006 017124 INI db: Loading titledb-saved.dat.
20180121-025233-000 0006 017124 INI db: Loading tagdb-saved.dat.
20180121-025233-081 0006 017124 INI db: Loading spiderdb-saved.dat.
20180121-025233-809 0006 017124 INI db: Loading doledb-saved.dat.
20180121-025234-218 0006 017124 INI db: Loading clusterdb-saved.dat.
20180121-025234-284 0006 017124 INI db: Loading linkdb-saved.dat.
20180121-025234-481 0006 017124 DBG Cleaning up any unfinished merges of main posdb
20180121-025234-481 0006 017124 DBG Found 5 .dat files for posdb
20180121-025234-481 0006 017124 DBG Found 1 .dat files for posdb in merge-space
20180121-025234-481 0006 017124 DBG Cleaned up any unfinished merges of main posdb
20180121-025235-641 0006 017124 WRN db: found leftover merge file in merge dir: /srv/gigablast/host6/merge//6/coll.main.0/posdb0024.002.0027.dat
20180121-025237-543 0006 017124 WRN db: Reading 128000 again from posdb (need 64000 total got 0 totalListSizes=237258 sk=0x000000000000000000000000000000000000) cn=0 this=0x7fbeb5be31a0 round=1.
20180121-025237-554 0006 017124 WRN db: Reading 128000 again from posdb (need 64000 total got 0 totalListSizes=231570 sk=0x000000000000000000000000000000000000) cn=0 this=0x7fbeb5be31a0 round=2.
20180121-025237-556 0006 017124 WRN db: Reading 128000 again from posdb (need 64000 total got 0 totalListSizes=267474 sk=0x000000000000000000000000000000000000) cn=0 this=0x7fbeb5be31a0 round=3.
20180121-025237-561 0006 017124 WRN db: Reading 128000 again from posdb (need 64000 total got 44268 totalListSizes=221430 sk=0x000000000000000000000000000000000000) cn=0 this=0x7fbeb5be31a0 round=4.
20180121-025237-582 0006 017124 DBG Cleaning up any unfinished merges of main titledb
20180121-025237-582 0006 017124 DBG Found 5 .dat files for titledb
20180121-025237-582 0006 017124 DBG Found 0 .dat files for titledb in merge-space
20180121-025237-582 0006 017124 DBG Cleaned up any unfinished merges of main titledb
20180121-025238-222 0006 017124 DBG Cleaning up any unfinished merges of main tagdb
20180121-025238-222 0006 017124 DBG Found 1 .dat files for tagdb
20180121-025238-222 0006 017124 DBG Found 0 .dat files for tagdb in merge-space
20180121-025238-222 0006 017124 DBG Cleaned up any unfinished merges of main tagdb
20180121-025238-310 0006 017124 DBG Cleaning up any unfinished merges of main clusterdb
20180121-025238-311 0006 017124 DBG Found 1 .dat files for clusterdb
20180121-025238-311 0006 017124 DBG Found 0 .dat files for clusterdb in merge-space
20180121-025238-311 0006 017124 DBG Cleaned up any unfinished merges of main clusterdb
20180121-025238-370 0006 017124 DBG Cleaning up any unfinished merges of main linkdb
20180121-025238-371 0006 017124 DBG Found 5 .dat files for linkdb
20180121-025238-371 0006 017124 DBG Found 0 .dat files for linkdb in merge-space
20180121-025238-371 0006 017124 DBG Cleaned up any unfinished merges of main linkdb
20180121-025238-734 0006 017124 DBG Cleaning up any unfinished merges of main spiderdb
20180121-025238-742 0006 017124 DBG Found 1 .dat files for spiderdb
20180121-025238-742 0006 017124 DBG Found 0 .dat files for spiderdb in merge-space
20180121-025238-742 0006 017124 DBG Cleaned up any unfinished merges of main spiderdb
20180121-025238-974 0006 017124 DBG Cleaning up any unfinished merges of main doledb
20180121-025238-975 0006 017124 DBG Found 0 .dat files for doledb
20180121-025238-975 0006 017124 DBG Found 0 .dat files for doledb in merge-space
20180121-025238-975 0006 017124 DBG Cleaned up any unfinished merges of main doledb
20180121-025238-983 0006 017124 DBG Loading high_frequency_term_posdb_shortcuts.dat
20180121-025238-983 0006 017124 DBG Loading page_temperatures.dat
20180121-025238-983 0006 017124 DBG Loading docid2flagsandsitemap.dat
20180121-025239-325 0006 017124 DBG table: grewtable udictht from 2097152 to 8388608 slots in 56 ms (this=0x55e05e6434a0) (used=0)
20180121-025239-824 0006 017124 DBG gb: unifiedDict-buf.txt or unifiedDict-map.dat checksum is not approved for live service (1974148069587949864 != -14450509118443930)
20180121-025239-911 0006 017124 INI udp: Listening on UDP port 9006 with fd=24.
20180121-025239-911 0006 017124 INI db: Loading cache from /srv/gigablast/host6//dns.cache
20180121-025239-932 0006 017124 INI udp: Listening on UDP port 6006 with fd=25.
20180121-025239-932 0006 017124 INI dns: Sending requests on client port 6006
20180121-025239-932 0006 017124 INI dns: Using nameserver 8.8.8.8:53.
20180121-025239-932 0006 017124 INI dns: Using nameserver 8.8.4.4:53.
20180121-025239-932 0006 017124 INI dns: Using nameserver 195.186.4.111:53.
20180121-025239-932 0006 017124 INI dns: Using nameserver 195.186.1.111:53.
20180121-025239-938 0006 017124 INI http: Listening on TCP port 8006 with sd=26
20180121-025239-939 0006 017124 INI https: Listening on TCP port 7006 with sd=27
20180121-025239-939 0006 017124 INI db: Loading cache from /srv/gigablast/host6//robots.txt.cache
20180121-025239-980 0006 017164 WRN vagus: got 15 alive hosts instead of 16
20180121-025239-980 0006 017164 WRN vagus: ++++++.+++++++++
20180121-025239-989 0006 017163 ERR Could not connect to url classification services, most recent errno=111 (Connection refused)
20180121-025240-012 0006 017145 DBG Old pid 16646 found in /tmp/gb_merge_locks/lock0, or errno=3
20180121-025240-046 0006 017124 INI db: Loading waitingtree-saved.dat.
20180121-025240-058 0006 017124 INI db: Growing tree to make room for waitingtree-saved.dat
20180121-025240-069 0006 017124 DBG table: grewtable waittbl from 2048 to 4096 slots in 0 ms (this=0x7fbdd50bcee8) (used=1024)
20180121-025240-070 0006 017124 DBG table: grewtable waittbl from 4096 to 8192 slots in 0 ms (this=0x7fbdd50bcee8) (used=2048)
20180121-025240-071 0006 017124 DBG table: grewtable waittbl from 8192 to 16384 slots in 0 ms (this=0x7fbdd50bcee8) (used=4096)
20180121-025240-078 0006 017124 DBG table: grewtable doleip from 2048 to 4096 slots in 0 ms (this=0x7fbdd50bcf88) (used=1024)
20180121-025240-078 0006 017124 DBG table: grewtable doleip from 4096 to 8192 slots in 0 ms (this=0x7fbdd50bcf88) (used=2048)
20180121-025240-079 0006 017124 DBG table: grewtable doleip from 8192 to 16384 slots in 1 ms (this=0x7fbdd50bcf88) (used=4096)
20180121-025240-085 0006 017124 DBG table: grewtable doleip from 16384 to 32768 slots in 1 ms (this=0x7fbdd50bcf88) (used=8192)
20180121-025240-091 0006 017124 DBG table: grewtable doleip from 32768 to 65536 slots in 0 ms (this=0x7fbdd50bcf88) (used=16384)
20180121-025240-108 0006 017124 DBG table: grewtable doleip from 65536 to 131072 slots in 3 ms (this=0x7fbdd50bcf88) (used=32768)
20180121-025240-149 0006 017124 DBG table: grewtable doleip from 131072 to 262144 slots in 5 ms (this=0x7fbdd50bcf88) (used=65536)
20180121-025240-211 0006 017124 DBG table: grewtable doleip from 262144 to 524288 slots in 8 ms (this=0x7fbdd50bcf88) (used=131072)
20180121-025240-331 0006 017124 DBG table: grewtable doleip from 524288 to 1048576 slots in 15 ms (this=0x7fbdd50bcf88) (used=262144)
20180121-025240-358 0006 017124 DBG spider: made spidercoll=7fbdd50bbc20 for cr=7fbeb0067470
20180121-025240-359 0006 017124 ERR Msg4In.cpp:handleRequest4:108: call sendErrorReply
20180121-025240-359 0006 017124 WRN Msg4In.cpp:handleRequest4: END - EWAITINGTOSYNCHOSTCONF
20180121-025240-359 0006 017124 WRN heartbeatWrapper: elapsed=369ms - is main thread slow?
20180121-025240-747 0006 017124 ERR Msg4In.cpp:handleRequest4:164: call sendErrorReply
20180121-025240-876 0006 017132 WRN Disk read of 622609 bytes took 79 ms
20180121-025240-879 0006 017124 ERR Msg4In.cpp:handleRequest4:164: call sendErrorReply
20180121-025240-977 0006 017124 DBG parms: trying to sync with host #0
20180121-025240-978 0006 017124 DBG parms: handling updated parameters (request type 3f)
20180121-025240-978 0006 017124 DBG parms: got parm update request. size=5347.
20180121-025240-979 0006 017124 DBG parms: updating parm "spidering enabled" (se[-1]) (collnum=-1) from "1" -> "0"
20180121-025240-980 0006 017124 DBG parmdb: running function for parm "in sync" (collnum=-1) args="(null)"
20180121-025240-980 0006 017124 DBG parms: sending parm update reply
20180121-025240-980 0006 017124 DBG parms: synced with host #0
20180121-025241-012 0006 017145 DBG MergeSpaceCoordinator::acquire: got lock #0 for 140064363426 bytes
20180121-025241-012 0006 017124 WRN db: merge: Regenerating map/index from a killed merge.
20180121-025242-559 0006 017146 INF db: Read 500000000 bytes [posdb0024.002.0027.dat]
20180121-025244-084 0006 017146 INF db: Read 1000000000 bytes [posdb0024.002.0027.dat]
20180121-025244-402 0006 017146 WRN db: Map generation failed because last record in data file was split. Power failure while writing? Truncating file to 1112715258 bytes. (lost 6 bytes)
20180121-025244-484 0006 017164 WRN vagus: got 14 alive hosts instead of 16
20180121-025244-484 0006 017164 WRN vagus: ++++++++++.++++.
20180121-025248-472 0006 017146 INF db: Read 500000000 bytes [posdb0024.002.0027.dat]
20180121-025249-487 0006 017164 WRN vagus: got 14 alive hosts instead of 16
20180121-025249-487 0006 017164 WRN vagus: ++++++++..++++++
20180121-025253-384 0006 017146 INF db: Read 1000000000 bytes [posdb0024.002.0027.dat]
20180121-025254-493 0006 017164 WRN vagus: got 13 alive hosts instead of 16
20180121-025254-493 0006 017164 WRN vagus: +++++++++.++.+.+
20180121-025305-815 0006 016808 ERR gbstart.sh: GB died, core dumped
```

lastcore.bt.txt:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./gb -l'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055e05daf437b in RdbList::getKey (this=this@entry=0x7fbea67ebcc0, rec=rec@entry=0x7fbd90000964 "\003\362\370k\341\025\n\314\334('\354\003\352\374k\256\023\n<\334Ȫ\372\001\n\374k\035\b\001\234\327=g\232\236\064\224\301/\311\001\372\374'", key=key@entry=0x7fbea67ebca0 "\001\362\370k\341\025\001\200OQ\210\r\353\260\355\360t\311~\246\276\177") at RdbList.cpp:532
532				memcpy ( key+12 ,m_listPtrHi,6);
#0  0x000055e05daf437b in RdbList::getKey (this=this@entry=0x7fbea67ebcc0, rec=rec@entry=0x7fbd90000964 "\003\362\370k\341\025\n\314\334('\354\003\352\374k\256\023\n<\334Ȫ\372\001\n\374k\035\b\001\234\327=g\232\236\064\224\301/\311\001\372\374'", key=key@entry=0x7fbea67ebca0 "\001\362\370k\341\025\001\200OQ\210\r\353\260\355\360t\311~\246\276\177") at RdbList.cpp:532
#1  0x000055e05daec3e6 in RdbList::getCurrentKey (key=0x7fbea67ebca0, this=0x7fbea67ebcc0) at RdbList.h:162
#2  RdbIndex::generateIndex (this=<optimized out>, f=<optimized out>) at RdbIndex.cpp:650
#3  0x000055e05d9e4611 in RdbMerge::regenerateFilesWrapper (state=0x55e05e63b280 <g_merge>) at RdbMerge.cpp:195
#4  0x000055e05d94f68d in (anonymous namespace)::job_pool_thread_function (pv=0x7fbeb00073c0) at JobScheduler.cpp:138
#5  0x00007fbec8fca494 in start_thread (arg=0x7fbea67ec700) at pthread_create.c:333
#6  0x00007fbec66ebaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by kjin9174** [comment]
Hello
I 've already checked your issue.
Could we help each other?
I have this issue.
If my privacore runs, i have no any result

20180202-201131-153 0000 002613 INI conf: Gigablast Version      : Jan 31 2018 09:00:58
20180202-201131-153 0000 002613 INI conf: Gigablast Architecture : 64-bit
20180202-201131-153 0000 002613 INI conf: Gigablast Build config : release
20180202-201131-153 0000 002613 INI conf: Gigablast Git commit   : 70f8867ca4f9dbc85f2558e553f537f6f1797f85
20180202-201131-153 0000 002613 DBG host: Working directory is /home/creuog/privacore/
20180202-201131-153 0000 002613 DBG host: Using /home/creuog/privacore/hosts.conf
20180202-201131-153 0000 002613 DBG host: Process ID is 2613
20180202-201131-153 0000 002613 DBG host: Detected local ip 127.0.0.1
20180202-201131-153 0000 002613 DBG host: Detected local ip 10.0.2.15
20180202-201131-153 0000 002613 DBG host: Running as host id #0
20180202-201131-162 0000 002613 INF wikt: Loading /home/creuog/privacore/wiktionary-syns.dat
20180202-201131-282 0000 002613 INF wikt: Loading /home/creuog/privacore/wiktionary-buf.txt
20180202-201131-296 0000 002613 DBG wikt: test "love" -> "en|love,loved,loving,loves"
20180202-201131-296 0000 002613 DBG main: initializing word variations: Danish
20180202-201131-296 0000 002613 WRN word-variation-danish initialization failed
20180202-201131-296 0000 002613 DBG main: initialized word variations: Danish
20180202-201131-296 0000 002613 INF wiki: Loading /home/creuog/privacore/wikititles2.dat
20180202-201131-296 0000 002613 INF mem: addMem(100663296): tbl-wiki. ptr=0x7ff5ce85f014 used=127540710
20180202-201131-365 0000 002613 INF db: Loading conf for collection main (0)
20180202-201131-366 0000 002613 INF db: Loading conf for collection global (1)
20180202-201131-367 0000 002613 INF mem: addMem(349879400): buckets-posdb. ptr=0x7ff5b9ab3014 used=228329538
20180202-201131-368 0000 002613 INF mem: addMem(193164080): mem-titledb. ptr=0x7ff5adec0014 used=586121018
20180202-201131-463 0000 002613 INF mem: addMem(100000022): mem-spiderdb. ptr=0x7ff59b121014 used=995497676
20180202-201131-501 0000 002613 INI db: Loading spiderdb-saved.dat.
20180202-201131-502 0000 002613 INF spider: nuking Doledb periodically is enabled, interval = 86400 seconds
20180202-201131-534 0000 002613 INI db: Loading doledb-saved.dat.
20180202-201131-535 0000 002613 DBG Cleaning up any unfinished merges of main posdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for posdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for posdb in merge-space
20180202-201131-536 0000 002613 DBG Cleaned up any unfinished merges of main posdb
20180202-201131-536 0000 002613 INF db: Generating global index for posdb
20180202-201131-536 0000 002613 INF db: Generated global index for posdb
20180202-201131-536 0000 002613 DBG Cleaning up any unfinished merges of main titledb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for titledb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for titledb in merge-space
20180202-201131-536 0000 002613 DBG Cleaned up any unfinished merges of main titledb
20180202-201131-536 0000 002613 DBG Cleaning up any unfinished merges of main tagdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for tagdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for tagdb in merge-space
20180202-201131-536 0000 002613 DBG Cleaned up any unfinished merges of main tagdb
20180202-201131-536 0000 002613 DBG Cleaning up any unfinished merges of main clusterdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for clusterdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for clusterdb in merge-space
20180202-201131-536 0000 002613 DBG Cleaned up any unfinished merges of main clusterdb
20180202-201131-536 0000 002613 DBG Cleaning up any unfinished merges of main linkdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for linkdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for linkdb in merge-space
20180202-201131-536 0000 002613 DBG Cleaned up any unfinished merges of main linkdb
20180202-201131-536 0000 002613 DBG Cleaning up any unfinished merges of main spiderdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for spiderdb
20180202-201131-536 0000 002613 DBG Found 0 .dat files for spiderdb in merge-space
20180202-201131-537 0000 002613 DBG Cleaned up any unfinished merges of main spiderdb
20180202-201131-537 0000 002613 DBG Cleaning up any unfinished merges of main doledb
20180202-201131-537 0000 002613 DBG Found 0 .dat files for doledb
20180202-201131-537 0000 002613 DBG Found 0 .dat files for doledb in merge-space
20180202-201131-537 0000 002613 DBG Cleaned up any unfinished merges of main doledb
20180202-201131-537 0000 002613 DBG Cleaning up any unfinished merges of global posdb
20180202-201131-537 0000 002613 DBG Found 0 .dat files for posdb
20180202-201131-537 0000 002613 DBG Found 0 .dat files for posdb in merge-space
20180202-201131-537 0000 002613 DBG Cleaned up any unfinished merges of global posdb
20180202-201131-537 0000 002613 INF db: Generating global index for posdb
20180202-201131-537 0000 002613 INF db: Generated global index for posdb
20180202-201131-537 0000 002613 DBG Cleaning up any unfinished merges of global titledb
20180202-201131-537 0000 002613 DBG Found 0 .dat files for titledb
20180202-201131-537 0000 002613 DBG Found 0 .dat files for titledb in merge-space
20180202-201131-537 0000 002613 DBG Cleaned up any unfinished merges of global titledb
20180202-201131-538 0000 002613 DBG Cleaning up any unfinished merges of global tagdb
20180202-201131-538 0000 002613 DBG Found 0 .dat files for tagdb
20180202-201131-538 0000 002613 DBG Found 0 .dat files for tagdb i
...................
................
